# Generated by Django 2.2.9 on 2020-07-10 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('journal_id', models.CharField(max_length=100)),
                ('journal_title', models.CharField(max_length=999)),
                ('ISSN', models.IntegerField()),
                ('publisher_name', models.CharField(max_length=256)),
                ('publisher_loc', models.CharField(max_length=256)),
                ('article_id_pmid', models.IntegerField()),
                ('article_id_pmc', models.CharField(max_length=256)),
                ('article_id_doi', models.CharField(max_length=999)),
                ('article_subject', models.CharField(max_length=999)),
                ('article_title', models.CharField(max_length=999)),
                ('contrib_surname', models.CharField(max_length=999)),
                ('contrib_given_names', models.CharField(max_length=999)),
                ('aff', models.TextField()),
                ('aff_label', models.CharField(max_length=256)),
                ('pub_date_ppub_day', models.IntegerField()),
                ('pub_date_ppub_month', models.IntegerField()),
                ('pub_date_ppub_year', models.IntegerField()),
                ('pub_date_epub_day', models.IntegerField()),
                ('pub_date_epub_month', models.IntegerField()),
                ('pub_date_epub_year', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('issue', models.IntegerField()),
                ('fpage', models.IntegerField()),
                ('lpage', models.IntegerField()),
                ('history_date_received_day', models.IntegerField()),
                ('history_date_received_month', models.IntegerField()),
                ('history_date_received_year', models.IntegerField()),
                ('history_rev_request_day', models.IntegerField()),
                ('history_rev_request_month', models.IntegerField()),
                ('history_rev_request_year', models.IntegerField()),
                ('history_rev_recd_day', models.IntegerField()),
                ('history_rev_recd_month', models.IntegerField()),
                ('history_rev_recd_year', models.IntegerField()),
                ('history_accepted_day', models.IntegerField()),
                ('history_accepted_month', models.IntegerField()),
                ('history_accepted_year', models.IntegerField()),
                ('copyright_statement', models.TextField()),
                ('abstract', models.TextField()),
                ('kwd', models.CharField(max_length=999)),
                ('sec_methods_title', models.CharField(max_length=999)),
                ('sec_methods_content', models.TextField()),
                ('sec_title', models.CharField(max_length=999)),
                ('sec_content', models.TextField()),
                ('ref_list_citation_surname', models.CharField(max_length=999)),
                ('ref_list_citation_given_names', models.CharField(max_length=999)),
                ('ref_list_article_title', models.CharField(max_length=999)),
                ('ref_list_source', models.CharField(max_length=999)),
                ('ref_list_year', models.IntegerField()),
                ('ref_list_volume', models.IntegerField()),
                ('ref_list_fpage', models.IntegerField()),
                ('ref_list_lpage', models.IntegerField()),
                ('ref_list_pub_id_pmid', models.IntegerField()),
                ('ref_list_pub_id_doi', models.IntegerField()),
                ('sec_display_objects_title', models.CharField(max_length=999)),
                ('sec_display_objects', models.TextField()),
                ('sec_display_objects_foot', models.TextField()),
            ],
        ),
    ]
