# Generated by Django 2.2.9 on 2020-07-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200720_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_id_publisher_id',
            field=models.CharField(default=0, max_length=9999),
            preserve_default=False,
        ),
    ]
