# Generated by Django 2.2.9 on 2020-07-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_article_id_publisher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_id_pmid',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fpage',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='articles',
            name='issue',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='articles',
            name='lpage',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='articles',
            name='volume',
            field=models.CharField(max_length=9999),
        ),
    ]
